name: Publicar en ElClaustro.cl
description: Envia tu contenido desde Github!
title: "[Ingresa el título a publicar] "
labels: ["Noticias"]
assignees:
  - ngeorger
body:
  - type: markdown
    attributes:
      value: |
        ![](https://raw.githubusercontent.com/sredevopsdev/elclaustro/main/static/images/wp-content/logo.png)
        
        # Publicar en ElClaustro.cl

        Gracias por el tiempo para enviar tu contenido.
  - type: input
    id: author
    attributes:
      label: Autor
      description: Cómo te gustaría que aparezcas como autor?
      placeholder: "Ejemplo: Alias o Nombre"
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: Categoria
      description: En qué categoría deseas publicar?
      options:
        - Noticias
        - Discos Y Multimedia
        - Entrevistas
        - Columnas
        - Otra
    validations:
      required: true
  - type: textarea    
    id: image
    attributes:
      label: image
      description: ¿Tienes una imagen para acompañar tu contenido?
      placeholder: "Arrastra y suelta tu imagen aquí o la URL de la imagen"
      # render: bash
    validations:
      required: false
  - type: textarea
    id: contenido
    attributes:
      label: Contenido
      description: Puedes copiar y pegar el contenido de tu publicación, o editar directamente con Markdown (Editor integrado 🧛🏻‍♂️)
      placeholder: Aquí arriba puedes usar el editor integrado 👆🏻
    validations:
      required: true
  - type: markdown
    attributes: 
      value: |
        
        ## Términos y condiciones
        
        Al enviar tu contenido, aceptas que sea publicado en ElClaustro.cl bajo [licecia Creative Commons NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
