name: "Convert issues to markdowns"
on:
  issues:
    types: [opened, edited ]
    
  workflow_dispatch:
    
jobs:
  convert_issues_to_markdown_job:
    runs-on: ubuntu-latest
    name: Convert issues to markdown.
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Fetch issues and generate markdowns
        uses: sredevopsdev/hugo-with-github-issues@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: 'testing-hugo-with-github-issues'
          owner: 'ngeorger'
          skip-author: 'utterances-bot'
          use-issue-seperator: 'true'
          output: 'content/posts'
          issue-state: 'open'
          skip-pull-requests: 'true'
      - name: Commit files
        run: |
          git config --local user.email "{{ secrets.GITHUB_EMAIL }}"
          git config --local user.name "{{ secrets.GITHUB_USERNAME }}"
          date > generated.txt
          git add .
          git commit -m "generated"
          git push
